<?php
namespace Database\Seeders;

use App\Models\Movie;
use Illuminate\Database\Seeder;

class MovieSeeder extends Seeder
{
    public function run()
    {
        $movies = [
            [
                'title'       => 'The Shawshank Redemption',
                'poster'      => 'The_Shawshank_Redemption',
                'trailer_url' => 'https://www.youtube.com/embed/6hB3S9bIaco',
                'year'        => 1994,
                'description' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Godfather',
                'poster'      => 'The_Godfather',
                'trailer_url' => 'https://www.youtube.com/embed/UaVTIH8mujA',
                'year'        => 1972,
                'description' => 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Dark Knight',
                'poster'      => 'The_Dark_Knight',
                'trailer_url' => 'https://www.youtube.com/embed/EXeTwQWrcwY',
                'year'        => 2008,
                'description' => 'When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Godfather: Part II',
                'poster'      => 'The_Godfather_Part_II',
                'trailer_url' => 'https://www.youtube.com/embed/9O1Iy9od7-A',
                'year'        => 1974,
                'description' => 'The early life and career of Vito Corleone in 1920s New York; the rise of his son Michael Corleone to power in the 1950s.',
                'type'        => 'movie',
            ],
            [
                'title'       => '12 Angry Men',
                'poster'      => '12_Angry_Men',
                'trailer_url' => 'https://www.youtube.com/embed/TEN-2uTi2c0',
                'year'        => 1957,
                'description' => 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'Schindler\'s List',
                'poster'      => 'Schindlers_List',
                'trailer_url' => 'https://www.youtube.com/embed/mxphAlJID9U',
                'year'        => 1993,
                'description' => 'In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Lord of the Rings: The Return of the King',
                'poster'      => 'The_Lord_of_the_Rings_The_Return_of_the_King',
                'trailer_url' => 'https://www.youtube.com/embed/r5X-hFf6Bwo',
                'year'        => 2003,
                'description' => 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'Pulp Fiction',
                'poster'      => 'Pulp_Fiction',
                'trailer_url' => 'https://www.youtube.com/embed/s7EdQ4FqbhY',
                'year'        => 1994,
                'description' => 'The lives of two mob hitmen, a boxer, a gangster\'s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Lord of the Rings: The Fellowship of the Ring',
                'poster'      => 'The_Lord_of_the_Rings_The_Fellowship_of_the_Ring',
                'trailer_url' => 'https://www.youtube.com/embed/V75dMMIW2B4',
                'year'        => 2001,
                'description' => 'A young hobbit, Frodo Baggins, is tasked with the dangerous mission of destroying the One Ring in the fires of Mount Doom.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Good, the Bad and the Ugly',
                'poster'      => 'The_Good_the_Bad_and_the_Ugly',
                'trailer_url' => 'https://www.youtube.com/embed/WCN5JJY_wiA',
                'year'        => 1966,
                'description' => 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'Forrest Gump',
                'poster'      => 'Forrest_Gump',
                'trailer_url' => 'https://www.youtube.com/embed/bLvqoHBptjg',
                'year'        => 1994,
                'description' => 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an extraordinary life.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'Inception',
                'poster'      => 'Inception',
                'trailer_url' => 'https://www.youtube.com/embed/YoHD9XEInc0',
                'year'        => 2010,
                'description' => 'A thief who enters the dreams of others to steal secrets from their subconscious is given the inverse task of planting an idea into the mind of a CEO.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Empire Strikes Back',
                'poster'      => 'The_Empire_Strikes_Back',
                'trailer_url' => 'https://www.youtube.com/embed/1g3_CFmnU7o',
                'year'        => 1980,
                'description' => 'After the rebels are overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Dark Knight Rises',
                'poster'      => 'The_Dark_Knight_Rises',
                'trailer_url' => 'https://www.youtube.com/embed/g8evyE9TuYk',
                'year'        => 2012,
                'description' => 'Eight years after the Joker\'s reign of anarchy, the Dark Knight is forced to resurface when a new terrorist leader, Bane, overwhelms Gotham\'s finest.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Matrix',
                'poster'      => 'The_Matrix',
                'trailer_url' => 'https://www.youtube.com/embed/m8e-FF8MsqU',
                'year'        => 1999,
                'description' => 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'Goodfellas',
                'poster'      => 'Goodfellas',
                'trailer_url' => 'https://www.youtube.com/embed/qo5jJpHtI1Y',
                'year'        => 1990,
                'description' => 'The story of Henry Hill and his life in the mob, covering his relationship with his wife and his mob partners.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Silence of the Lambs',
                'poster'      => 'The_Silence_of_the_Lambs',
                'trailer_url' => 'https://www.youtube.com/embed/29Zp6aY5QdM',
                'year'        => 1991,
                'description' => 'A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer who skins his victims.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'Se7en',
                'poster'      => 'Se7en',
                'trailer_url' => 'https://www.youtube.com/embed/znmZoVkCjpI',
                'year'        => 1995,
                'description' => 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'Fight Club',
                'poster'      => 'Fight_Club',
                'trailer_url' => 'https://www.youtube.com/embed/SUXWAEX2jlg',
                'year'        => 1999,
                'description' => 'An insomniac office worker and a soap maker form an underground fight club that evolves into something much more.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'Interstellar',
                'poster'      => 'Interstellar',
                'trailer_url' => 'https://www.youtube.com/embed/zSWdZVtXT7E',
                'year'        => 2014,
                'description' => 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'Parasite',
                'poster'      => 'Parasite',
                'trailer_url' => 'https://www.youtube.com/embed/5xH0HfJHsaY',
                'year'        => 2019,
                'description' => 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Green Mile',
                'poster'      => 'The_Green_Mile',
                'trailer_url' => 'https://www.youtube.com/embed/ktjafK4SgWM',
                'year'        => 1999,
                'description' => 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'Gladiator',
                'poster'      => 'Gladiator',
                'trailer_url' => 'https://www.youtube.com/embed/owK1qxDselE',
                'year'        => 2000,
                'description' => 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'Whiplash',
                'poster'      => 'Whiplash',
                'trailer_url' => 'https://www.youtube.com/embed/7d_jQycdQGo',
                'year'        => 2014,
                'description' => 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Prestige',
                'poster'      => 'The_Prestige',
                'trailer_url' => 'https://www.youtube.com/embed/o4gHCmTQDVI',
                'year'        => 2006,
                'description' => 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Lion King',
                'poster'      => 'The_Lion_King',
                'trailer_url' => 'https://www.youtube.com/embed/4sj1MT05lAA',
                'year'        => 1994,
                'description' => 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'The Departed',
                'poster'      => 'The_Departed',
                'trailer_url' => 'https://www.youtube.com/embed/iojhqm0JTW4',
                'year'        => 2006,
                'description' => 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in Boston.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'Joker',
                'poster'      => 'Joker',
                'trailer_url' => 'https://www.youtube.com/embed/zAGVQLHvwOY',
                'year'        => 2019,
                'description' => 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.',
                'type'        => 'movie',
            ],
            [
                'title'       => 'Breaking Bad',
                'poster'      => 'Breaking_Bad',
                'trailer_url' => 'https://www.youtube.com/embed/HhesaQXLuRY',
                'year'        => 2008,
                'description' => 'A high school chemistry teacher turned methamphetamine producer navigates the dangers of the criminal world.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'Game of Thrones',
                'poster'      => 'Game_of_Thrones',
                'trailer_url' => 'https://www.youtube.com/embed/BpJYNVhGf1s',
                'year'        => 2011,
                'description' => 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'Stranger Things',
                'poster'      => 'Stranger_Things',
                'trailer_url' => 'https://www.youtube.com/embed/mnd7sFt5c3A',
                'year'        => 2016,
                'description' => 'A group of kids in a small town uncover supernatural forces and secret government exploits while searching for their missing friend.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'The Crown',
                'poster'      => 'The_Crown',
                'trailer_url' => 'https://www.youtube.com/embed/JWtnJjn6ng0',
                'year'        => 2016,
                'description' => 'Chronicles the life of Queen Elizabeth II from the 1940s to modern times, depicting political and personal events that shaped the monarchy.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'The Mandalorian',
                'poster'      => 'The_Mandalorian',
                'trailer_url' => 'https://www.youtube.com/embed/aOC8E8z_ifw',
                'year'        => 2019,
                'description' => 'A lone bounty hunter in the outer reaches of the galaxy protects a mysterious child while navigating the remnants of the Empire.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'The Boys',
                'poster'      => 'The_Boys',
                'trailer_url' => 'https://www.youtube.com/embed/pq8TUo7ZSOQ',
                'year'        => 2019,
                'description' => 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'Westworld',
                'poster'      => 'Westworld',
                'trailer_url' => 'https://www.youtube.com/embed/2r2evjNDDiA',
                'year'        => 2016,
                'description' => 'A futuristic amusement park populated by androids allows guests to live out their fantasies, but secrets of the park emerge.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'Mindhunter',
                'poster'      => 'Mindhunter',
                'trailer_url' => 'https://www.youtube.com/embed/3vHykq8B9TI',
                'year'        => 2017,
                'description' => 'FBI agents develop criminal profiling and behavioral science techniques while interviewing serial killers.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'Sherlock',
                'poster'      => 'Sherlock',
                'trailer_url' => 'https://www.youtube.com/embed/xK7S9mrFWL4',
                'year'        => 2010,
                'description' => 'A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'House of Cards',
                'poster'      => 'House_of_Cards',
                'trailer_url' => 'https://www.youtube.com/embed/ULwUzF1q5w4',
                'year'        => 2013,
                'description' => 'A ruthless politician and his wife manipulate their way through Washington D.C. to gain power at all costs.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'Chernobyl',
                'poster'      => 'Chernobyl',
                'trailer_url' => 'https://www.youtube.com/embed/s9APLXM9Ei8',
                'year'        => 2019,
                'description' => 'Dramatizes the 1986 nuclear disaster and the aftermath, including the cleanup efforts and the sacrifices made by first responders.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'Vikings',
                'poster'      => 'Vikings',
                'trailer_url' => 'https://www.youtube.com/embed/1qM1XUuZQbE',
                'year'        => 2013,
                'description' => 'Follows the adventures of Ragnar Lothbrok, the legendary Viking chieftain, and his family as they raid and conquer territories.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'The Witcher',
                'poster'      => 'The_Witcher',
                'trailer_url' => 'https://www.youtube.com/embed/ndl1W4ltcmg',
                'year'        => 2019,
                'description' => 'Geralt of Rivia, a monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'Narcos',
                'poster'      => 'Narcos',
                'trailer_url' => 'https://www.youtube.com/embed/U7elNhHwgBU',
                'year'        => 2015,
                'description' => 'Follows the rise of the cocaine trade in Colombia and the gripping real-life stories of drug lords.',
                'type'        => 'tv_show',
            ],
            [
                'title'       => 'Ozark',
                'poster'      => 'Ozark',
                'trailer_url' => 'https://www.youtube.com/embed/FLn0NB37asE',
                'year'        => 2017,
                'description' => 'A financial planner relocates his family to the Ozarks and becomes entangled with dangerous criminal organizations.',
                'type'        => 'tv_show',
            ],
        ];

        foreach ($movies as $movie) {
            Movie::create($movie);
        }
    }
}
